### ISSUE TITLE
Cease using default Cesium Bing maps key

### ISSUE THREAD

**Issue by axman6** [NICTA/aremi-natmap#1]
From the console log for aremi.nicta.com.au:

"[Log] This application is using Cesium's default Bing Maps key.  Please create a new key for the application as soon as possible and prior to deployment by visiting https://www.bingmapsportal.com/, and provide your key to Cesium by setting the Cesium.BingMapsApi.defaultKey property before constructing the CesiumWidget or any other object that uses the Bing Maps API. (ausglobe.js, line 28)"

**Comment by meh9** [comment]
GA now includes an AREMI Bing key in deployment.
