### ISSUE TITLE
investigate using the AEMO network diagram map

### ISSUE THREAD

**Issue by meh9** [NICTA/aremi-natmap#13]
We need to figure out if it is possible use this map on AREMI:

http://www.aemo.com.au/electricity/planning/interactive-map/#

**Comment by kring** [comment]
Looks like it's a simple tiled server using the OpenStreetMap tiling scheme.  Should be easy to connect to it.

**Comment by meh9** [comment]
Investigated, found suitable needs:

https://github.com/TerriaJS/terriajs/pull/897
